Feature branch
Abidoyinsola1/embed-video-project pull request #1
Opened 2020-06-01 13:14 UTC by Abidoyinsola1

2020-06-01 13:21 UTC, santiago-rodrig commented
# Pull Request under review by @santiago-rodrig (TSE)

2020-06-01 13:26 UTC, santiago-dev96 requested changes
# Changes required 🚫

Please make sure that your PR and README (this one has a wrong heading) are professional before submitting a CRR (Code Review Request).

Friendly reminder: You should make sure that your repo looks professional before review.
Please take a step back and read a lesson [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/). Then apply 3 simple rules from this lesson (it will be easy as you can use a template provided there). This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

After implementing the required changes submit another CRR.

You can reach out to me in slack as **srodrig**, happy coding! :wave:

2020-06-01 23:47 UTC, addod19 commented
> _No description provided._

Let us edit the PR with some title and description. For instance, title => youtube clone, description => CSS flex and float for position elements, sans-serif for font-family or something insteresting

2020-06-01 23:48 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-06-02 00:13 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @Abidoyinsola1, great job :+1: Commit messages clearly but can be improved :slightly_smiling_face:  Let us work to get the project approved by addressing the comments below:
- ``` Nav ```, the elements in the nav needs a little work. Input and social icons
![unav](https://user-images.githubusercontent.com/46388113/83465331-19cffc80-a463-11ea-9083-d97aa9c3eab4.png)
- ``` Main ```, the main content is overlapping with the sidebar
![min](https://user-images.githubusercontent.com/46388113/83465413-5f8cc500-a463-11ea-901f-6eb7574a8b0f.png)
- ``` Share and Subscribe Button ```, currently we have a share and subscribe icon, let us change them to button
![sb](https://user-images.githubusercontent.com/46388113/83465654-230d9900-a464-11ea-83c9-c3e87bb3c86b.png)
![sb1](https://user-images.githubusercontent.com/46388113/83465706-4cc6c000-a464-11ea-805e-bd723d9508bd.png)
- Let us fix the error returned by the w3validator
![err](https://user-images.githubusercontent.com/46388113/83465821-b34bde00-a464-11ea-88cf-fa37c7bb5dbb.png)
- Let us apply the DRY rule. The following CSS properties have been repeated; ``` display: flex ```, ``` position: absolute ```, ``` display: grid ``` appears more than once. Let us refactor our file
- In our README file, we are repeating ```Built with and Completed with ```, let us remove on and try so add more light to our description :smiley: 

Kindly make these changes and submit another code review :+1: 
_Happy coding_ :man_technologist:
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/) for any clarification or details

2020-06-02 00:13 UTC, addod19 commented on index.html
> +        </div>
Let us improve semantics by using ```<aside>``` instead of ```< div class="sidebar">```

2020-06-03 01:04 UTC, lucasmazo32 requested changes
# Changes required :wrench:

You are doing a great job so far, and the project is looking good. 

For the project to get approved, kindly implement this change:

> ![image](https://user-images.githubusercontent.com/57414789/83584206-0b89eb00-a50c-11ea-8d68-7a34601fdada.png)

- [ ] Kindly fix overlap of the save and share buttons.

### Happy coding! :computer:

## Lucas Mazo

2020-06-03 10:39 UTC, HADDADSOHAIB commented
> ### Pull Request under the review by Sohaib Haddad. (TSE)

### Hello @Abidoyinsola1  :handshake: 

### Good job so far :clap:  your project is looking good :medal_sports: 

### there are still some changes requested by the previous TSE to make to get the project approved :point_down: 

- There is still a lot of overlap in your project:
![Screenshot from 2020-06-03 11-31-13](https://user-images.githubusercontent.com/26064042/83626923-12f1d880-a58e-11ea-94d9-ad56363e8fe2.png)
![Screenshot from 2020-06-03 11-31-21](https://user-images.githubusercontent.com/26064042/83626928-15543280-a58e-11ea-80d0-c7b0a2f79835.png)
- Please add descriptive comments to the pull request as requested from the previous TSE:
- your pull request:
![Screenshot from 2020-06-03 11-35-07](https://user-images.githubusercontent.com/26064042/83627148-68c68080-a58e-11ea-8b01-f0fe607d3401.png)
- you can follow this propositions for a title a description:
![Screenshot from 2020-06-03 11-35-19](https://user-images.githubusercontent.com/26064042/83627232-8398f500-a58e-11ea-8878-4b47cea11b49.png)
- The subscribe and share should be buttons, they are not in your project:
- [ ] It has a share button ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_share_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))

- [ ] It has a subscribe button ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_subscribe_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))

### Please implement the changes and ask for another code review, good job so far :+1:

2020-06-03 13:40 UTC, peterrobert commented
### PULL REQUEST UNDER REVIEW BY PETER ROBERT

2020-06-03 13:48 UTC, peterrobert approved these changes
### APPROVED :+1: 
Great work implementing the required changes. I have approved this project but there are some more changes required. Kindly Improve on the following

-  Your search bar needs to be properly positioned at the center of the page.

-  The like and dislike should be buttons but not icons. Try using a CSS  rule to make the cursor to be a pointer.

Great work :clap: kindly do those changes and submit a project completion form. I have approved it because you have made the changes required in the previous reviews. 
on to the next project :fireworks:  Happy coding:computer:

2020-06-03 14:04 UTC, merged